export const productConstants = {
  FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
  FETCH_USER_FAILURE: 'FETCH_USER_FAILURE',
  FETCH_SUCCESS: 'FETCH_SUCCESS',
  FETCH_FAILURE: 'FETCH_FAILURE',
  PURCHASE_PRODUCT_SUCCESS: 'PURCHASE_PRODUCT_SUCCESS',
  PURCHASE_PRODUCT_FAILURE: 'PURCHASE_PRODUCT_FAILURE'
};
